"""
Helpers for building self-contained ``bsp export`` bundles.

A bundle is a directory that contains everything needed to reproduce a build
on another machine:

* the exported configuration (KAS YAML or Android repo manifest XML),
* every patch file referenced by the exported KAS configuration,
* a ``setup.sh`` shell script performing the initial build setup.
"""

import logging
import shutil
from pathlib import Path
from typing import List, Optional

# Name of the generated initial-setup shell script.
SETUP_SCRIPT_NAME = "setup.sh"
# Default file names used when exporting into a bundle directory.
DEFAULT_KAS_CONFIG_NAME = "kas.yml"
DEFAULT_REPO_MANIFEST_NAME = "manifest.xml"
# Sub-directory used for patches that live outside the registry root.
EXTERNAL_PATCH_DIR = "patches"


def _safe_relative_path(source: Path, base_dir: Optional[Path]) -> Path:
    """
    Return the bundle-relative destination path for *source*.

    Patches below *base_dir* keep their relative layout so that the paths
    recorded in the exported KAS configuration stay valid.  Anything else is
    placed flat inside :data:`EXTERNAL_PATCH_DIR`.
    """
    if base_dir is not None:
        try:
            relative = source.relative_to(base_dir)
        except ValueError:
            relative = None
        if relative is not None and not relative.is_absolute():
            return relative
    return Path(EXTERNAL_PATCH_DIR) / source.name


def copy_patches(
    patch_files: List[str],
    export_dir: str,
    base_dir: Optional[str] = None,
) -> List[Path]:
    """
    Copy patch files into the export bundle.

    Args:
        patch_files: Absolute paths of the patch files to copy
        export_dir: Bundle directory the patches are copied into
        base_dir: Registry root used to preserve the relative patch layout

    Returns:
        List of bundle-relative paths of the copied patches
    """
    export_path = Path(export_dir).resolve()
    base_path = Path(base_dir).resolve() if base_dir else None

    copied: List[Path] = []
    seen = set()

    for patch_file in patch_files:
        source = Path(patch_file)
        if not source.is_absolute():
            source = (base_path or export_path) / source
        source = source.resolve()

        if not source.is_file():
            logging.warning(f"Patch file not found, skipping: {source}")
            continue

        relative = _safe_relative_path(source, base_path)
        if relative in seen:
            continue
        seen.add(relative)

        destination = export_path / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        copied.append(relative)

    if copied:
        logging.info(f"Copied {len(copied)} patch file(s) to {export_path}")
    else:
        logging.debug("No patch files to copy")

    return copied


def _escape_double_quoted(text: str) -> str:
    """Escape *text* for safe interpolation inside a double-quoted shell string."""
    for char in ("\\", '"', "$", "`"):
        text = text.replace(char, "\\" + char)
    return text


def _sanitize_comment(text: str) -> str:
    """Collapse *text* into a single line safe for a shell comment."""
    return " ".join(str(text).split())


def _kas_setup_script(config_name: str, label: str) -> str:
    """Return the contents of the KAS flavour of the setup script."""
    return f"""#!/bin/sh
# Initial build setup for: {label}
# Generated by bsp-registry-tools -- edit freely.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
KAS_CONFIG="${{KAS_CONFIG:-$SCRIPT_DIR/{config_name}}}"
BUILD_DIR="${{KAS_BUILD_DIR:-$SCRIPT_DIR/build}}"

if ! command -v kas >/dev/null 2>&1; then
    echo "kas is not installed. Install it with: pip install kas" >&2
    exit 1
fi

if [ ! -f "$KAS_CONFIG" ]; then
    echo "KAS configuration not found: $KAS_CONFIG" >&2
    exit 1
fi

mkdir -p "$BUILD_DIR"
export KAS_BUILD_DIR="$BUILD_DIR"

echo "Fetching layers for $KAS_CONFIG ..."
kas checkout "$KAS_CONFIG"

if [ "${{1:-}}" = "--build" ]; then
    shift
    echo "Starting build ..."
    kas build "$KAS_CONFIG" "$@"
else
    echo "Layers are ready. Start a build with:"
    echo "  kas build $KAS_CONFIG"
    echo "or open a shell with:"
    echo "  kas shell $KAS_CONFIG"
fi
"""


def _repo_setup_script(config_name: str, label: str) -> str:
    """Return the contents of the Android ``repo`` flavour of the setup script."""
    return f"""#!/bin/sh
# Initial build setup for: {label}
# Generated by bsp-registry-tools -- edit freely.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MANIFEST="${{REPO_MANIFEST:-$SCRIPT_DIR/{config_name}}}"
MANIFEST_REPO="$SCRIPT_DIR/.manifest-repo"

if ! command -v repo >/dev/null 2>&1; then
    echo "repo is not installed. See https://gerrit.googlesource.com/git-repo" >&2
    exit 1
fi

if [ ! -f "$MANIFEST" ]; then
    echo "Repo manifest not found: $MANIFEST" >&2
    exit 1
fi

# `repo init` requires a git repository holding the manifest, so wrap the
# exported manifest in a local one.
rm -rf "$MANIFEST_REPO"
mkdir -p "$MANIFEST_REPO"
cp "$MANIFEST" "$MANIFEST_REPO/default.xml"
git -C "$MANIFEST_REPO" init -q
git -C "$MANIFEST_REPO" add default.xml
git -C "$MANIFEST_REPO" -c user.email=bsp@example.com -c user.name=bsp \\
    commit -q -m "Exported manifest"

echo "Initialising repo workspace ..."
repo init -u "$MANIFEST_REPO" -m default.xml
repo sync "$@"

echo "Sources are ready in $SCRIPT_DIR"
"""


def generate_setup_script(
    export_dir: str,
    config_name: str,
    repo_manifest: bool = False,
    label: str = "",
) -> Path:
    """
    Write the initial build setup shell script into the bundle.

    Args:
        export_dir: Bundle directory the script is written to
        config_name: Bundle-relative name of the exported configuration
        repo_manifest: Whether the configuration is an Android repo manifest
        label: Human readable description of the exported configuration

    Returns:
        Path to the generated script
    """
    export_path = Path(export_dir)
    export_path.mkdir(parents=True, exist_ok=True)
    script_path = export_path / SETUP_SCRIPT_NAME

    label = _sanitize_comment(label) or "BSP export"
    safe_config_name = _escape_double_quoted(config_name)
    content = (
        _repo_setup_script(safe_config_name, label)
        if repo_manifest
        else _kas_setup_script(safe_config_name, label)
    )

    script_path.write_text(content, encoding="utf-8")
    script_path.chmod(0o755)

    logging.info(f"Setup script generated: {script_path}")
    return script_path
